---
include:
 # - board: eyelash_sofle_left
#    shield: nice_view
  - board: eyelash_sofle_right
    # shield: nice_view_custom
    shield: urchin_right nice_view_custom # https://github.com/GPeye/urchin-peripheral-animation?tab=readme-ov-file
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left
  - board: eyelash_sofle_left
    shield: settings_reset
